### ISSUE TITLE
Will there be a demo ?

### ISSUE THREAD

**Issue by AboutRSS** [yindaheng98/RSSBot#1]
Hi. Thanks for your creation. Will there be a demo bot? For instance, return RSS Feed URL generated based on RSSHub route when receiving URL like Twitter account.

**Comment by yindaheng98** [comment]
Hello! Thank you for your interest in the program! 

Unfortunately, there will not be an open demo for this program. This is because the program is designed to subscribe the generated RSS Feed URL to your RSS reader (e.g. TTRSS), rather than simply generating a Feed URL. Besides, this program is so simple that the location of RSS reader is just fixed in the config. If a demo were opened, any URLs sent to it would be subscribed to the creator's RSS reader, which would not be ideal. 

You can still use your program in a simple way by using Docker: https://github.com/yindaheng98/RSSBot#use-it
